apiVersion: batch/v1
kind: Job
metadata:
  name: telemetrygen-logs
  namespace: glassflow
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: telemetrygen
          image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
          args:
            - logs
            - '--otlp-header=x-glassflow-pipeline-id="otlp-logs"'
            - --otlp-endpoint=glassflow-otlp-receiver.glassflow.svc.cluster.local:4317
            - --otlp-insecure
            - --duration=50m
            - --rate=50
            - --batch-size=1000


