// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/glassflow/clickhouse-etl-internal/glassflow-api/internal/schema_v2 (interfaces: DBClient)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/dbclient_mock.go -package mocks . DBClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/glassflow/clickhouse-etl-internal/glassflow-api/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDBClient is a mock of DBClient interface.
type MockDBClient struct {
	ctrl     *gomock.Controller
	recorder *MockDBClientMockRecorder
	isgomock struct{}
}

// MockDBClientMockRecorder is the mock recorder for MockDBClient.
type MockDBClientMockRecorder struct {
	mock *MockDBClient
}

// NewMockDBClient creates a new mock instance.
func NewMockDBClient(ctrl *gomock.Controller) *MockDBClient {
	mock := &MockDBClient{ctrl: ctrl}
	mock.recorder = &MockDBClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBClient) EXPECT() *MockDBClientMockRecorder {
	return m.recorder
}

// GetLatestSchemaVersion mocks base method.
func (m *MockDBClient) GetLatestSchemaVersion(ctx context.Context, schemaID string) (*models.SchemaVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestSchemaVersion", ctx, schemaID)
	ret0, _ := ret[0].(*models.SchemaVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestSchemaVersion indicates an expected call of GetLatestSchemaVersion.
func (mr *MockDBClientMockRecorder) GetLatestSchemaVersion(ctx, schemaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestSchemaVersion", reflect.TypeOf((*MockDBClient)(nil).GetLatestSchemaVersion), ctx, schemaID)
}

// GetMappingsBySchema mocks base method.
func (m *MockDBClient) GetMappingsBySchema(ctx context.Context, sourceID, schemaID string, orientation models.MappingOrintation) ([]*models.Mapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMappingsBySchema", ctx, sourceID, schemaID, orientation)
	ret0, _ := ret[0].([]*models.Mapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMappingsBySchema indicates an expected call of GetMappingsBySchema.
func (mr *MockDBClientMockRecorder) GetMappingsBySchema(ctx, sourceID, schemaID, orientation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMappingsBySchema", reflect.TypeOf((*MockDBClient)(nil).GetMappingsBySchema), ctx, sourceID, schemaID, orientation)
}

// GetSchema mocks base method.
func (m *MockDBClient) GetSchema(ctx context.Context, schemaID string) (*models.SchemaV2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchema", ctx, schemaID)
	ret0, _ := ret[0].(*models.SchemaV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchema indicates an expected call of GetSchema.
func (mr *MockDBClientMockRecorder) GetSchema(ctx, schemaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchema", reflect.TypeOf((*MockDBClient)(nil).GetSchema), ctx, schemaID)
}

// GetSchemaVersion mocks base method.
func (m *MockDBClient) GetSchemaVersion(ctx context.Context, schemaID, version string) (*models.SchemaVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchemaVersion", ctx, schemaID, version)
	ret0, _ := ret[0].(*models.SchemaVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchemaVersion indicates an expected call of GetSchemaVersion.
func (mr *MockDBClientMockRecorder) GetSchemaVersion(ctx, schemaID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchemaVersion", reflect.TypeOf((*MockDBClient)(nil).GetSchemaVersion), ctx, schemaID, version)
}

// SaveSchemaVersion mocks base method.
func (m *MockDBClient) SaveSchemaVersion(ctx context.Context, schemaVersion models.SchemaVersion, sourceMappings, destinationMappings []*models.Mapping) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSchemaVersion", ctx, schemaVersion, sourceMappings, destinationMappings)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSchemaVersion indicates an expected call of SaveSchemaVersion.
func (mr *MockDBClientMockRecorder) SaveSchemaVersion(ctx, schemaVersion, sourceMappings, destinationMappings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSchemaVersion", reflect.TypeOf((*MockDBClient)(nil).SaveSchemaVersion), ctx, schemaVersion, sourceMappings, destinationMappings)
}
