// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/glassflow/clickhouse-etl-internal/glassflow-api/internal/api (interfaces: PipelineService)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/pipeline_service_mock.go -package mocks . PipelineService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/glassflow/clickhouse-etl-internal/glassflow-api/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockPipelineService is a mock of PipelineService interface.
type MockPipelineService struct {
	ctrl     *gomock.Controller
	recorder *MockPipelineServiceMockRecorder
	isgomock struct{}
}

// MockPipelineServiceMockRecorder is the mock recorder for MockPipelineService.
type MockPipelineServiceMockRecorder struct {
	mock *MockPipelineService
}

// NewMockPipelineService creates a new mock instance.
func NewMockPipelineService(ctrl *gomock.Controller) *MockPipelineService {
	mock := &MockPipelineService{ctrl: ctrl}
	mock.recorder = &MockPipelineServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPipelineService) EXPECT() *MockPipelineServiceMockRecorder {
	return m.recorder
}

// CleanUpPipelines mocks base method.
func (m *MockPipelineService) CleanUpPipelines(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanUpPipelines", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanUpPipelines indicates an expected call of CleanUpPipelines.
func (mr *MockPipelineServiceMockRecorder) CleanUpPipelines(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanUpPipelines", reflect.TypeOf((*MockPipelineService)(nil).CleanUpPipelines), ctx)
}

// CreatePipeline mocks base method.
func (m *MockPipelineService) CreatePipeline(ctx context.Context, cfg *models.PipelineConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePipeline", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePipeline indicates an expected call of CreatePipeline.
func (mr *MockPipelineServiceMockRecorder) CreatePipeline(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePipeline", reflect.TypeOf((*MockPipelineService)(nil).CreatePipeline), ctx, cfg)
}

// DeletePipeline mocks base method.
func (m *MockPipelineService) DeletePipeline(ctx context.Context, pid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePipeline", ctx, pid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePipeline indicates an expected call of DeletePipeline.
func (mr *MockPipelineServiceMockRecorder) DeletePipeline(ctx, pid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePipeline", reflect.TypeOf((*MockPipelineService)(nil).DeletePipeline), ctx, pid)
}

// EditPipeline mocks base method.
func (m *MockPipelineService) EditPipeline(ctx context.Context, pid string, newCfg *models.PipelineConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditPipeline", ctx, pid, newCfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditPipeline indicates an expected call of EditPipeline.
func (mr *MockPipelineServiceMockRecorder) EditPipeline(ctx, pid, newCfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditPipeline", reflect.TypeOf((*MockPipelineService)(nil).EditPipeline), ctx, pid, newCfg)
}

// GetOrchestratorType mocks base method.
func (m *MockPipelineService) GetOrchestratorType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrchestratorType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetOrchestratorType indicates an expected call of GetOrchestratorType.
func (mr *MockPipelineServiceMockRecorder) GetOrchestratorType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrchestratorType", reflect.TypeOf((*MockPipelineService)(nil).GetOrchestratorType))
}

// GetPipeline mocks base method.
func (m *MockPipelineService) GetPipeline(ctx context.Context, pid string, sourceSchemaVersions map[string]string) (models.PipelineConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipeline", ctx, pid, sourceSchemaVersions)
	ret0, _ := ret[0].(models.PipelineConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipeline indicates an expected call of GetPipeline.
func (mr *MockPipelineServiceMockRecorder) GetPipeline(ctx, pid, sourceSchemaVersions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipeline", reflect.TypeOf((*MockPipelineService)(nil).GetPipeline), ctx, pid, sourceSchemaVersions)
}

// GetPipelineHealth mocks base method.
func (m *MockPipelineService) GetPipelineHealth(ctx context.Context, pid string) (models.PipelineHealth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelineHealth", ctx, pid)
	ret0, _ := ret[0].(models.PipelineHealth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelineHealth indicates an expected call of GetPipelineHealth.
func (mr *MockPipelineServiceMockRecorder) GetPipelineHealth(ctx, pid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelineHealth", reflect.TypeOf((*MockPipelineService)(nil).GetPipelineHealth), ctx, pid)
}

// GetPipelineResources mocks base method.
func (m *MockPipelineService) GetPipelineResources(ctx context.Context, pid string) (*models.PipelineResourcesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelineResources", ctx, pid)
	ret0, _ := ret[0].(*models.PipelineResourcesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelineResources indicates an expected call of GetPipelineResources.
func (mr *MockPipelineServiceMockRecorder) GetPipelineResources(ctx, pid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelineResources", reflect.TypeOf((*MockPipelineService)(nil).GetPipelineResources), ctx, pid)
}

// GetPipelines mocks base method.
func (m *MockPipelineService) GetPipelines(ctx context.Context) ([]models.ListPipelineConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelines", ctx)
	ret0, _ := ret[0].([]models.ListPipelineConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelines indicates an expected call of GetPipelines.
func (mr *MockPipelineServiceMockRecorder) GetPipelines(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelines", reflect.TypeOf((*MockPipelineService)(nil).GetPipelines), ctx)
}

// ResumePipeline mocks base method.
func (m *MockPipelineService) ResumePipeline(ctx context.Context, pid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumePipeline", ctx, pid)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumePipeline indicates an expected call of ResumePipeline.
func (mr *MockPipelineServiceMockRecorder) ResumePipeline(ctx, pid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumePipeline", reflect.TypeOf((*MockPipelineService)(nil).ResumePipeline), ctx, pid)
}

// StopPipeline mocks base method.
func (m *MockPipelineService) StopPipeline(ctx context.Context, pid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopPipeline", ctx, pid)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopPipeline indicates an expected call of StopPipeline.
func (mr *MockPipelineServiceMockRecorder) StopPipeline(ctx, pid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopPipeline", reflect.TypeOf((*MockPipelineService)(nil).StopPipeline), ctx, pid)
}

// TerminatePipeline mocks base method.
func (m *MockPipelineService) TerminatePipeline(ctx context.Context, pid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminatePipeline", ctx, pid)
	ret0, _ := ret[0].(error)
	return ret0
}

// TerminatePipeline indicates an expected call of TerminatePipeline.
func (mr *MockPipelineServiceMockRecorder) TerminatePipeline(ctx, pid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminatePipeline", reflect.TypeOf((*MockPipelineService)(nil).TerminatePipeline), ctx, pid)
}

// UpdatePipelineMetadata mocks base method.
func (m *MockPipelineService) UpdatePipelineMetadata(ctx context.Context, id string, metadata models.PipelineMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePipelineMetadata", ctx, id, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePipelineMetadata indicates an expected call of UpdatePipelineMetadata.
func (mr *MockPipelineServiceMockRecorder) UpdatePipelineMetadata(ctx, id, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipelineMetadata", reflect.TypeOf((*MockPipelineService)(nil).UpdatePipelineMetadata), ctx, id, metadata)
}

// UpdatePipelineName mocks base method.
func (m *MockPipelineService) UpdatePipelineName(ctx context.Context, id, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePipelineName", ctx, id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePipelineName indicates an expected call of UpdatePipelineName.
func (mr *MockPipelineServiceMockRecorder) UpdatePipelineName(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipelineName", reflect.TypeOf((*MockPipelineService)(nil).UpdatePipelineName), ctx, id, name)
}

// UpdatePipelineResources mocks base method.
func (m *MockPipelineService) UpdatePipelineResources(ctx context.Context, pid string, resources models.PipelineResources) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePipelineResources", ctx, pid, resources)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePipelineResources indicates an expected call of UpdatePipelineResources.
func (mr *MockPipelineServiceMockRecorder) UpdatePipelineResources(ctx, pid, resources any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipelineResources", reflect.TypeOf((*MockPipelineService)(nil).UpdatePipelineResources), ctx, pid, resources)
}
