services:
  nats:
    image: nats:alpine
    ports:
      - 4222:4222
      - 8222:8222
    command: --js
    healthcheck:
      test: wget http://localhost:8222/healthz -q -S -O -
      start_period: 3s
      retries: 3
      timeout: 3s
      interval: 10s

  bridge:
    depends_on:
      nats:
        condition: service_healthy
    build: .
    env_file: ".env"

