import { NextConfig } from 'next'

const config: NextConfig = {
  reactStrictMode: true,
  images: {
    domains: ['localhost'],
  },
  env: {
    NEXT_PUBLIC_USE_MOCK_API: process.env.NEXT_PUBLIC_USE_MOCK_API,
    NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
    NEXT_PUBLIC_IN_DOCKER: process.env.NEXT_PUBLIC_IN_DOCKER,
    NEXT_PUBLIC_PREVIEW_MODE: process.env.NEXT_PUBLIC_PREVIEW_MODE,
    NEXT_PUBLIC_ANALYTICS_ENABLED: process.env.NEXT_PUBLIC_ANALYTICS_ENABLED,
    NEXT_PUBLIC_DEMO_MODE: process.env.NEXT_PUBLIC_DEMO_MODE,
    NEXT_PUBLIC_DASHBOARD: process.env.NEXT_PUBLIC_DASHBOARD,
    NEXT_PUBLIC_AUTH0_ENABLED: process.env.NEXT_PUBLIC_AUTH0_ENABLED,
    NEXT_PUBLIC_PROFILE_ROUTE: process.env.NEXT_PUBLIC_PROFILE_ROUTE,
    NEXT_PUBLIC_FILTERS_ENABLED: process.env.NEXT_PUBLIC_FILTERS_ENABLED,
    // OpenTelemetry configuration
    NEXT_PUBLIC_OTEL_LOGS_ENABLED: process.env.NEXT_PUBLIC_OTEL_LOGS_ENABLED,
    NEXT_PUBLIC_OTEL_METRICS_ENABLED: process.env.NEXT_PUBLIC_OTEL_METRICS_ENABLED,
    NEXT_PUBLIC_OTEL_SERVICE_NAME: process.env.NEXT_PUBLIC_OTEL_SERVICE_NAME,
    NEXT_PUBLIC_OTEL_SERVICE_VERSION: process.env.NEXT_PUBLIC_OTEL_SERVICE_VERSION,
    NEXT_PUBLIC_OTEL_SERVICE_NAMESPACE: process.env.NEXT_PUBLIC_OTEL_SERVICE_NAMESPACE,
    NEXT_PUBLIC_OTEL_SERVICE_INSTANCE_ID: process.env.NEXT_PUBLIC_OTEL_SERVICE_INSTANCE_ID,
    NEXT_PUBLIC_OTEL_EXPORTER_OTLP_ENDPOINT: process.env.NEXT_PUBLIC_OTEL_EXPORTER_OTLP_ENDPOINT,
    NEXT_PUBLIC_OTEL_EXPORTER_OTLP_HEADERS: process.env.NEXT_PUBLIC_OTEL_EXPORTER_OTLP_HEADERS,
    NEXT_PUBLIC_LOG_LEVEL: process.env.NEXT_PUBLIC_LOG_LEVEL,
  },
  // Redirects are now handled by middleware.ts to support optional auth
}

export default config
