name: Merge to Main

on:
  push:
    branches:
      - main

jobs:
  build-binary:
    uses: ./.github/workflows/build_binary.yaml
  test:
    uses: ./.github/workflows/test.yaml
  build:
    needs:
      - build-binary
      - test
    uses: ./.github/workflows/build_image.yaml
    with:
      push: true
    secrets: inherit
