name: Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - glassflow-cloud

jobs:
  build-binary:
    uses: ./.github/workflows/build_binary.yaml
  test:
    needs:
      - build-binary
    uses: ./.github/workflows/test.yaml
  build:
    needs:
      - test
    uses: ./.github/workflows/build_image.yaml
    with:
      push: true
    secrets: inherit
