name: Push Tag

on:
  push:
    tags:
      - v*
  release:
    types: [published]

jobs:
  build-binary:
    uses: ./.github/workflows/build_binary.yaml
  build-and-release:
    needs:
      - build-binary
    uses: ./.github/workflows/build_image.yaml
    with:
      push: true
    secrets: inherit
  notify:
    needs: build-and-release
    uses: ./.github/workflows/notify.yaml
    secrets: inherit
