name: Push Tag

on:
  push:
    tags:
      - v*
  release:
    types: [published]

jobs:
  build-binary:
    uses: ./.github/workflows/build_binary.yaml
  build-and-release:
    needs:
      - build-binary
    uses: ./.github/workflows/build_image.yaml
    with:
      push: true
    secrets: inherit
  create-release:
    needs:
      - build-and-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract tag name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Generate changelog
        id: changelog
        run: |
          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")
          
          # Generate changelog
          if [ -n "$PREV_TAG" ]; then
            CHANGELOG=$(git log --pretty=format:"- %s (%h)" $PREV_TAG..HEAD)
          else
            CHANGELOG=$(git log --pretty=format:"- %s (%h)" --max-count=20)
          fi
          
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}
          release_name: Release ${{ steps.tag.outputs.TAG_NAME }}
          body: |
            ## What's Changed
            
            ${{ steps.changelog.outputs.CHANGELOG }}
            
            ## Docker Images
            
            The following Docker images are available with tag `${{ steps.tag.outputs.TAG_NAME }}`:
            
            - `ghcr.io/glassflow/glassflow-etl-be:${{ steps.tag.outputs.TAG_NAME }}`
            - `ghcr.io/glassflow/glassflow-etl-ingestor:${{ steps.tag.outputs.TAG_NAME }}`
            - `ghcr.io/glassflow/glassflow-etl-join:${{ steps.tag.outputs.TAG_NAME }}`
            - `ghcr.io/glassflow/glassflow-etl-sink:${{ steps.tag.outputs.TAG_NAME }}`
            - `ghcr.io/glassflow/glassflow-etl-fe:${{ steps.tag.outputs.TAG_NAME }}`
          draft: false
          prerelease: false
  notify:
    needs: build-and-release
    uses: ./.github/workflows/notify.yaml
    secrets: inherit
