name: Test Glassflow API
on:
  push:

jobs:
  test-api:
    name: test api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: './glassflow-api/go.mod'
          cache-dependency-path: './glassflow-api/go.mod'
      - name: Run test
        working-directory: './glassflow-api'
        run: make run-test
