name: Test Bridge
on:
  push:
    paths:
      - 'nats-kafka-bridge/**'

jobs:
  test-bridge:
    name: test kafka->nats bridge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: './nats-kafka-bridge/go.mod'
          cache-dependency-path: './nats-kafka-bridge/go.mod'
      - name: Run test
        working-directory: './nats-kafka-bridge'
        run: make run-test
